### PR TITLE
Routing fixes

### PR DESCRIPTION
**Pull request by sonkeks**
This is a major routing fix. Among some other changes we now are finally able to smoothly navigate through the App without any page transitioning twice. 

1. All major urls now have "/tabs" infront of the former name. We can put anything there, it is just all the pages where the user should have access to the Bottom Tabbar. I know it doesn't look that nice anymore but within the app we won't ever see the link anyways. It is just a Ionic Standard and we can't work around it sadly. It's just how React Router works.

Bildschirm­foto 2023-01-24 um 15 01 29

Bildschirm­foto 2023-01-24 um 15 01 37

etc.

2. On the Start, Login and Register Page, the Tabbar is now hidden, so that unregistered Users can't access the app.

Bildschirm­foto 2023-01-24 um 15 04 55

Bildschirm­foto 2023-01-24 um 15 05 03

Bildschirm­foto 2023-01-24 um 15 05 14

3. If the user is already logged in, quits the app and then opens it again (or visits the "/" url) he is redirected to the HomeTab which is finally making this feel like the landing page it was intended to be! 
4. If a user that has not logged in tries to visit any page except start, register and login, they are redirected to start. The redirect now works in any circumstance and multiple times.

I have tested this on web and on iOS and it works like Butter. Please test the navigation through the App ESPECIALLY the back buttons meaning switching between pages. If there is any weird navigation error, please report to me!

### CODE REVIEW

**Review by marinakuzminchuk — COMMENTED** [review]
I checked the navigation on android. After I logged in, the clubs tab opened, I pressed the "back" button on my phone and was redirected to the login page, which was blank and I had to login again. I think we shouldn't redirect to the login page if the user is logged in.

When I leave the club page sometimes I get back to the clubs tab and sometimes to the home tab, and it's not always where I came from to the club page.

**Comment by sonkeks** [comment]
The login page being blank on first start of the new build should be normal. Anyways this functionality of auto filling the login comes from the native environment, not from our app. Hm, we don't redirect to login when the user is logged in either... it is weird that these things are happening on your android phone, in the android simulator these things work all fine. Concerning the Hardware back button: I just found a possible solution for the problem, I will try to implement this :)

**Comment by sonkeks** [comment]
Okay, got an update on the issue with the Hardware Back Button on Android.
Apparently it REQUIRES manual settings in Ionic to get it to work. They explained it [here](https://ionicframework.com/docs/developing/hardware-back-button). 

However, I tried this in the App Component and even multiple pages seperately by mocking routing to specific pages when pressing the hardware back (for example routing from the club page back to the home tab or to the clubs tab). Somehow Android cannot use history nor the useIonRouter const and I cannot find a reason for that.

But the more interesting find: Hitting the hardware back button actually fires the event twice with just one click. This explains, why routing sometimes seems unconditional as it jumps two steps in the history except for one. Additionally it seems that some routing done by Ionic does not add to the android app history and is thereby ignored by the hardware back.

It also explains the mismatch of the hardware back navigation with the navigation within our App. They are not using the same history. The hardware back uses it's own history that can even surpass our routing system (because it does not use that).

Here is the event handler I built according to the Ionic Docs:

Bildschirm­foto 2023-01-25 um 00 50 23

In the following console logs from android studio you can see that the handler is called twice. The line above the prints however states the hardware back to be indeed only clicked once. 

Bildschirm­foto 2023-01-25 um 00 42 37

Additionally to that, any press on the hardware back in Android Studio logs this Error Message:

2023-01-25 00:42:36.578 648-679/system_process E/RemoteAugmentedAutofillService: Bad service name for flags 1048704: com.google.android.as/com.google.android.apps.miphone.aiai.app.AiAiAugmentedAutofillService

I cannot find anything about that error online though... If no one else has any idea for a solution, I'd suggest to disable the functionality of the hardware back button on android when using our app. By that we could secure a save and logical navigation on android at least.

**Review by marinakuzminchuk — APPROVED** [review]

**Comment by sonkeks** [comment]
The Tab bar is still visible on the Live Discussion and the routing needs some rework still. Gotta fix and reopen.

**Comment by de-JoKa** [comment]
Ich habe es gerade ausprobiert. Bei mir laufen die Transitions super! Allerdings komme ich, wenn ich eine LiveDiscussion beendet habe, beim klicken auf den Bakc-Button, wieder zurück in die LiveDiscussion. --> Das muss noch gefixed werden ;)

**Pull request merged**
